/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author nguye
 */
public class MenuItem extends javax.swing.JPanel {
  private boolean selected;
    public MenuItem(ModelMenu data) {
        initComponents();
         setOpaque(false);
        if (data.getType() == ModelMenu.MenuType.MENU) {
            lbl_icon.setIcon(data.toIcon());
            lbl_name.setText(data.getName());
        }else if(data.getType() == ModelMenu.MenuType.TITLE){
            lbl_icon.setText(data.getName());
            lbl_icon.setFont(new Font("sansserif",1,12));
            lbl_name.setVisible(false);
        }else{
            lbl_name.setText(" ");
        }
    }
        
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    
    }
   
    public MenuItem() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_icon = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_icon)
                .addGap(18, 18, 18)
                .addComponent(lbl_name)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     @Override
    protected void paintComponent(Graphics grphcs) {
       if(selected){
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(new Color(255, 255, 255,80));
        g2.fillRoundRect(10, 0, getWidth()-20, getHeight(), 5, 5);
       }
      
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify                     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_name;
    // End of variables declaration//GEN-END:variables
}
