/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.sanPham;

import entities.products.Chuoi;
import entities.products.DauCoBan;
import entities.products.MauSac;
import entities.products.Ngon;
import entities.products.Ren;
import entities.products.SanPhamChiTiet;
import entities.products.TayCam;
import entities.products.ThuocTinh;
import entities.products.ThuongHieu;
import entities.products.XuatXu;
import javax.swing.JOptionPane;
import org.apache.commons.math3.util.Pair;
import repositories.products.ChuoiRepository;
import repositories.products.DauCoBanRepository;
import repositories.products.MauSacRepository;
import repositories.products.NgonRepository;
import repositories.products.RenRepository;
import repositories.products.TayCamRepository;
import repositories.products.ThuongHieuRepository;
import repositories.products.XuatXuRepository;
import utils.MaGenerator;
import utils.validators.sanPhamChiTiet.SanPhamChiTietValidator;
import utils.validators.thuocTinh.ThuocTinhValidator;

/**
 *
 * @author Mtt
 */
public class ThuocTinhQuickCreateForm extends javax.swing.JFrame {

    /**
     * Creates new form ThuocTinhQuickCreateForm
     */
    private SanPhamChiTietCreateForm parent;
    private String table;

    public ThuocTinhQuickCreateForm(String table, SanPhamChiTietCreateForm parent) {
        initComponents();

        this.parent = parent;
        this.table = table;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNewThuocTinhTen = new javax.swing.JTextField();
        btnCreateThuocTinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateThuocTinh.setText("Tạo");
        btnCreateThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateThuocTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtNewThuocTinhTen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnCreateThuocTinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtNewThuocTinhTen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateThuocTinh)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateThuocTinhActionPerformed
        try {
            String newName = txtNewThuocTinhTen.getText();

            ThuocTinhValidator.validate(newName, table);

            if (JOptionPane.OK_OPTION != JOptionPane.showConfirmDialog(this, "Tạo?", "Tạo", JOptionPane.OK_CANCEL_OPTION)) {
                return;
            }

            switch (table) {
                case "chuoi":
                    new ChuoiRepository().create(Chuoi.builder().ma(MaGenerator.generate("CH")).ten(newName).build());
                    break;
                case "tay_cam":
                    new TayCamRepository().create(TayCam.builder().ma(MaGenerator.generate("TC")).ten(newName).build());
                    break;
                case "xuat_xu":
                    new XuatXuRepository().create(XuatXu.builder().ma(MaGenerator.generate("XX")).ten(newName).build());
                    break;
                case "dau_co_ban":
                    new DauCoBanRepository().create(DauCoBan.builder().ma(MaGenerator.generate("DBC")).ten(newName).build());
                    break;
                case "ngon":
                    new NgonRepository().create(Ngon.builder().ma(MaGenerator.generate("NG")).ten(newName).build());
                    break;
                case "ren":
                    new RenRepository().create(Ren.builder().ma(MaGenerator.generate("RN")).ten(newName).build());
                    break;
                case "thuong_hieu":
                    new ThuongHieuRepository().create(ThuongHieu.builder().ma(MaGenerator.generate("TH")).ten(newName).build());
                    break;
                case "mau_sac":
                    new MauSacRepository().create(MauSac.builder().ma(MaGenerator.generate("MS")).ten(newName).build());
                    break;
                default:
                    throw new RuntimeException("Thuộc tính không tồn tại");
            }
            parent.useCreatedThuocTinh(table, newName);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCreateThuocTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhQuickCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhQuickCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhQuickCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThuocTinhQuickCreateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateThuocTinh;
    private javax.swing.JTextField txtNewThuocTinhTen;
    // End of variables declaration//GEN-END:variables
}
